In [2]:
import numpy as np
list_ = [ '1' , '2' , '3' , '4' , '5' ]
array_list = np.array(object = list_)

In [6]:
# Q1. Is there any difference in the data type of variables list_ and array_list? If there is then write a code
# to print the data types of both the variables.
"""
list_ : Is a regular python list data type
array_list : Is a numpy array list both haveing same element
"""
print("Type of list: ",type(list_))
print("Type of array_list: ", type(array_list))

Type of list:  <class 'list'>
Type of array_list:  <class 'numpy.ndarray'>


In [7]:
# Q2. Write a code to print the data type of each and every element of both the variables list_ and
# arra_list.
print(type(list_[0]))
print(type(array_list[0]))

<class 'str'>
<class 'numpy.str_'>


In [11]:
# Q3. Considering the following changes in the variable, array_list:
array_list = np.array(object = list_, dtype = int)
# Will there be any difference in the data type of the elements present in both the variables, list_ and
# arra_list? If so then print the data types of each and every element present in both the variables, list_
# and arra_list.
print(type(list_))
print(type(array_list))
print(type(list_[0]))
print(type(array_list[0]))
for i in list_:
    print(type(i))
for j in array_list:
    print(type(j))

<class 'list'>
<class 'numpy.ndarray'>
<class 'str'>
<class 'numpy.int64'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'numpy.int64'>
<class 'numpy.int64'>
<class 'numpy.int64'>
<class 'numpy.int64'>
<class 'numpy.int64'>


In [14]:
# Consider the below code to answer further questions:
import numpy as np
num_list = [ [ 1 , 2 , 3 ] , [ 4 , 5 , 6 ] ]
num_array = np.array(object = num_list)
# Q4. Write a code to find the following characteristics of variable, num_array:
# (i) shape
# (ii) size
print(num_array.shape)
print(num_array.size)

(2, 3)
6


In [19]:
# Q5. Write a code to create numpy array of 3*3 matrix containing zeros only, using a numpy array
# creation function.
# [Hint: The size of the array will be 9 and the shape will be (3,3).]
num_array = np.zeros((3,3))
print(num_array)
print(num_array.shape)
print(num_array.size)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
(3, 3)
9


In [22]:
# Q6. Create an identity matrix of shape (5,5) using numpy functions?
# [Hint: An identity matrix is a matrix containing 1 diagonally and other elements will be 0.]
numpy_array = np.identity(5)
print(numpy_array)

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]
